spring:
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: false
  application:
    name: hexagonal
  datasource:
    url: jdbc:postgresql://localhost:5432/db_location
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 2005
